--CONCAT

SELECT 'NESLIHAN' +' '+'SEKER'

SELECT CONCAT('NESLIHAN',' ','SEKER')

SELECT CONCAT_WS(' ','NESLIHAN','SEKER')


SELECT 
USERNAME_+' '+PASSWORD_+' '+NAMESURNAME,
CONCAT(USERNAME_,' ',PASSWORD_,' ',NAMESURNAME),
CONCAT_WS (' ',USERNAME_,PASSWORD_,NAMESURNAME),


* FROM USERS

