--LEFT,RIGHT,LEN

SELECT LEFT ('NESLÝHAN ÞEKER',4) 
SELECT RIGHT ('NESLÝHAN ÞEKER',4) 
SELECT LEN('NESLÝHAN ÞEKER')

SELECT LEFT ('NESLÝHAN ÞEKER',8) 
SELECT LEFT ('NESLÝHAN ÞEKER',CHARINDEX(' ','NESLÝHAN ÞEKER')),
RIGHT ('NESLÝHAN ÞEKER',LEN('NESLÝHAN ÞEKER')-CHARINDEX(' ','NESLÝHAN ÞEKER')) 


 
SELECT LEFT (NAMESURNAME,CHARINDEX(' ',NAMESURNAME)),
RIGHT (NAMESURNAME,LEN(NAMESURNAME)-CHARINDEX(' ',NAMESURNAME)) 

 FROM USERS