--ORTALAMA TESLÝMAT SÜRESÝ
SELECT
DATEPART(YEAR,O.DATE_) AS YIL,
DATEPART(MONTH, O.DATE_) AS AY,
AVG(DATEDIFF(HOUR,O.DATE_,I.DATE_))AS ORT_TESLIMATSURESI,
MIN(DATEDIFF(HOUR,O.DATE_,I.DATE_))AS MIN_TESLIMATSURESI,
MAX(DATEDIFF(HOUR,O.DATE_,I.DATE_))AS MAX_TESLIMATSURESI,

SUM(O.TOTALPRICE) AS TOPLAMSIPARISTUTARI,
COUNT(O.ID) AS SIPARISSAYISI
FROM ORDERS O
	INNER JOIN USERS U ON U.ID=O.USERID
	INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
	INNER JOIN CITIES CT ON CT.ID=A.CITYID
	INNER JOIN TOWNS T ON T.ID=A.TOWNID
	INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
	INNER JOIN PAYMENTS P ON P.ORDERID= O.ID
	INNER JOIN INVOICES I ON I.ID=O.ID
	
GROUP BY DATEPART(YEAR, O.DATE_),
DATEPART(MONTH, O.DATE_)
ORDER BY 1,2 
