--KULLANICININ SON ADRESÝNÝ BULMA

SELECT U.*,
(SELECT TOP 1 ADDRESSTEXT FROM ADDRESS
WHERE USERID=U.ID ORDER BY ID DESC) SONADRES,
(SELECT TOP 1 ADDRESSTEXT FROM ADDRESS
WHERE USERID=U.ID ORDER BY ID ) ILKADRES,
(SELECT COUNT(ADDRESSTEXT) FROM ADDRESS
WHERE USERID=U.ID ) ADRESSAYISI


FROM USERS U

--,A.ADDRESSTEXT FROM USERS U
--INNER JOIN ADDRESS A ON A.USERID=U.ID

