--TARÝHE GÖRE SÝPARÝÞ DAÐILIMINI GETÝREN SORGU

SELECT 
	
	CONVERT(DATE,O.DATE_) TARIH,
	SUM(OD.LINETOTAL) TOPLAMSIPARIS,
	SUM(OD.AMOUNT)AS TOPLAMMSIPARIS_ADEDI,
	COUNT(OD.ID) AS TOPLAMSIPARIS_SAYISI
DATEPART(YEAR, DATE_) AS YIL,
DATEPART(MONTH, DATE_) AS AY,
ORDER BY CONVERT(DATE,O.DATE_)
