--ÜRÜN KATEGORÝLERÝNE GÖRE SÝPARÝÞ DAÐILIMI

SELECT 
	ITM.CATEGORY1 , ITM.CATEGORY2,--, ITM.CATEGORY3,ITM.CATEGORY4,
	SUM(OD.LINETOTAL)AS TOPLAMSIPARIS_TUTARI,
	SUM(OD.AMOUNT)AS TOPLAMMSIPARIS_ADEDI,
	COUNT(OD.ID) AS TOPLAMSIPARIS_SAYISI,
	SUM(OD.LINETOTAL)/SUM(OD.AMOUNT) AS ORTBIRIMFIYAT
FROM ORDERS O
	INNER JOIN USERS U ON U.ID=O.USERID
	INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
	INNER JOIN CITIES CT ON CT.ID=A.CITYID
	INNER JOIN TOWNS T ON T.ID=A.TOWNID
	INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
	INNER JOIN PAYMENTS P ON P.ORDERID= O.ID
	INNER JOIN INVOICES I ON I.ID=O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
	INNER JOIN ITEMS ITM ON ITM.ID=O.ID
--WHERE ITM.CATEGORY1='KOZMETIK'
GROUP BY ITM.CATEGORY1,ITM.CATEGORY2--,ITM.CATEGORY3,ITM.CATEGORY4
ORDER BY 1 DESC