--ÖDEME TÜRÜNE GÖRE DAÐILIM

SELECT  
DATEPART(YEAR, DATE_) AS YIL,
DATEPART(MONTH, DATE_) AS AY,

PAYMENTTYPE AS ODEMETURU,

CASE
   WHEN PAYMENTTYPE =1 THEN 'KREDI KARTI'
   WHEN PAYMENTTYPE =2 THEN 'BANKA KARTI'
END AS ODEMETURU_ACIKLAMA
FROM PAYMENTS

GROUP BY  DATEPART(MONTH, DATE_),DATEPART(YEAR, DATE_) ,PAYMENTTYPE
ORDER BY DATEPART(MONTH,DATE_) ,DATEPART(YEAR, DATE_) 