SELECT MIN(TOTALPRICE),MAX(TOTALPRICE),COUNT(ID),SUM(TOTALPRICE),AVG(TOTALPRICE)  

FROM SALES WHERE CITY='ADANA'


SELECT MIN(TOTALPRICE),MAX(TOTALPRICE),COUNT(ID),SUM(TOTALPRICE),AVG(TOTALPRICE)  

FROM SALES WHERE CITY='ÝSTANBUL'


