SELECT
TOP 10
CITY, SUM(TOTALPRICE) AS TOTALPRICE
--MIN(TOTALPRICE) AS MINPRICE,
--MAX(TOTALPRICE) AS MAXPRICE,
--COUNT(ID)       ROWCOUNT_,
--SUM(TOTALPRICE) AS TOTALPRICE,
--AVG(TOTALPRICE) AS AVGPRICE

FROM SALES
GROUP BY CITY
ORDER BY SUM(TOTALPRICE)DESC
 