--SUBSTRING FONKSIYONU
--SELECT SUBSTRING('NESLIHAN SEKER',1,8)

SELECT * FROM USERS WHERE USERNAME_ LIKE 'O%'

SELECT * FROM USERS WHERE SUBSTRING(USERNAME_,LEN(USERNAME_),1)='O'


SELECT LEN('A_KALKMAZO')
SELECT SUBSTRING ('A_KALKMAZO',10,1)